// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: BJFJFCDPFNG.proto
// </auto-generated>
#pragma warning disable 1591, 0612, 3021, 8981
#region Designer generated code

using pb = global::Google.Protobuf;
using pbc = global::Google.Protobuf.Collections;
using pbr = global::Google.Protobuf.Reflection;
using scg = global::System.Collections.Generic;
namespace March7thHoney.Proto {

  /// <summary>Holder for reflection information generated from BJFJFCDPFNG.proto</summary>
  public static partial class BJFJFCDPFNGReflection {

    #region Descriptor
    /// <summary>File descriptor for BJFJFCDPFNG.proto</summary>
    public static pbr::FileDescriptor Descriptor {
      get { return descriptor; }
    }
    private static pbr::FileDescriptor descriptor;

    static BJFJFCDPFNGReflection() {
      byte[] descriptorData = global::System.Convert.FromBase64String(
          string.Concat(
            "ChFCSkZKRkNEUEZORy5wcm90byqeAQoLQkpGSkZDRFBGTkcSGwoXQkpGSkZD",
            "RFBGTkdfREZOQk9ESU1JR0wQABIbChdCSkZKRkNEUEZOR19LREhKRk1EREFF",
            "RBABEhsKF0JKRkpGQ0RQRk5HX05EREpPTExGQ0hEEAISGwoXQkpGSkZDRFBG",
            "TkdfR0VQTU9CSEZITEEQAxIbChdCSkZKRkNEUEZOR19EQUJFRUdCRUdPUBAE",
            "QhaqAhNNYXJjaDd0aEhvbmV5LlByb3RvYgZwcm90bzM="));
      descriptor = pbr::FileDescriptor.FromGeneratedCode(descriptorData,
          new pbr::FileDescriptor[] { },
          new pbr::GeneratedClrTypeInfo(new[] {typeof(global::March7thHoney.Proto.BJFJFCDPFNG), }, null, null));
    }
    #endregion

  }
  #region Enums
  public enum BJFJFCDPFNG {
    [pbr::OriginalName("BJFJFCDPFNG_DFNBODIMIGL")] Dfnbodimigl = 0,
    [pbr::OriginalName("BJFJFCDPFNG_KDHJFMDDAED")] Kdhjfmddaed = 1,
    [pbr::OriginalName("BJFJFCDPFNG_NDDJOLLFCHD")] Nddjollfchd = 2,
    [pbr::OriginalName("BJFJFCDPFNG_GEPMOBHFHLA")] Gepmobhfhla = 3,
    [pbr::OriginalName("BJFJFCDPFNG_DABEEGBEGOP")] Dabeegbegop = 4,
  }

  #endregion

}

#endregion Designer generated code
