// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: BNDHJNDFFED.proto
// </auto-generated>
#pragma warning disable 1591, 0612, 3021, 8981
#region Designer generated code

using pb = global::Google.Protobuf;
using pbc = global::Google.Protobuf.Collections;
using pbr = global::Google.Protobuf.Reflection;
using scg = global::System.Collections.Generic;
namespace March7thHoney.Proto {

  /// <summary>Holder for reflection information generated from BNDHJNDFFED.proto</summary>
  public static partial class BNDHJNDFFEDReflection {

    #region Descriptor
    /// <summary>File descriptor for BNDHJNDFFED.proto</summary>
    public static pbr::FileDescriptor Descriptor {
      get { return descriptor; }
    }
    private static pbr::FileDescriptor descriptor;

    static BNDHJNDFFEDReflection() {
      byte[] descriptorData = global::System.Convert.FromBase64String(
          string.Concat(
            "ChFCTkRISk5ERkZFRC5wcm90bypkCgtCTkRISk5ERkZFRBIbChdCTkRISk5E",
            "RkZFRF9CSFBOUE9IQ0dMQRAAEhsKF0JOREhKTkRGRkVEX0FNSkNNQ0pEUEtE",
            "EAESGwoXQk5ESEpOREZGRURfTUhORk9JQ01CS00QAkIWqgITTWFyY2g3dGhI",
            "b25leS5Qcm90b2IGcHJvdG8z"));
      descriptor = pbr::FileDescriptor.FromGeneratedCode(descriptorData,
          new pbr::FileDescriptor[] { },
          new pbr::GeneratedClrTypeInfo(new[] {typeof(global::March7thHoney.Proto.BNDHJNDFFED), }, null, null));
    }
    #endregion

  }
  #region Enums
  public enum BNDHJNDFFED {
    [pbr::OriginalName("BNDHJNDFFED_BHPNPOHCGLA")] Bhpnpohcgla = 0,
    [pbr::OriginalName("BNDHJNDFFED_AMJCMCJDPKD")] Amjcmcjdpkd = 1,
    [pbr::OriginalName("BNDHJNDFFED_MHNFOICMBKM")] Mhnfoicmbkm = 2,
  }

  #endregion

}

#endregion Designer generated code
