// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: EBABBABOINF.proto
// </auto-generated>
#pragma warning disable 1591, 0612, 3021, 8981
#region Designer generated code

using pb = global::Google.Protobuf;
using pbc = global::Google.Protobuf.Collections;
using pbr = global::Google.Protobuf.Reflection;
using scg = global::System.Collections.Generic;
namespace March7thHoney.Proto {

  /// <summary>Holder for reflection information generated from EBABBABOINF.proto</summary>
  public static partial class EBABBABOINFReflection {

    #region Descriptor
    /// <summary>File descriptor for EBABBABOINF.proto</summary>
    public static pbr::FileDescriptor Descriptor {
      get { return descriptor; }
    }
    private static pbr::FileDescriptor descriptor;

    static EBABBABOINFReflection() {
      byte[] descriptorData = global::System.Convert.FromBase64String(
          string.Concat(
            "ChFFQkFCQkFCT0lORi5wcm90bypkCgtFQkFCQkFCT0lORhIbChdFQkFCQkFC",
            "T0lORl9QQ1BESEVMUEtFTRAAEhsKF0VCQUJCQUJPSU5GX0NEUExQSUJES05O",
            "EAESGwoXRUJBQkJBQk9JTkZfSkFJQUZQSk9ERkUQAkIWqgITTWFyY2g3dGhI",
            "b25leS5Qcm90b2IGcHJvdG8z"));
      descriptor = pbr::FileDescriptor.FromGeneratedCode(descriptorData,
          new pbr::FileDescriptor[] { },
          new pbr::GeneratedClrTypeInfo(new[] {typeof(global::March7thHoney.Proto.EBABBABOINF), }, null, null));
    }
    #endregion

  }
  #region Enums
  public enum EBABBABOINF {
    [pbr::OriginalName("EBABBABOINF_PCPDHELPKEM")] Pcpdhelpkem = 0,
    [pbr::OriginalName("EBABBABOINF_CDPLPIBDKNN")] Cdplpibdknn = 1,
    [pbr::OriginalName("EBABBABOINF_JAIAFPJODFE")] Jaiafpjodfe = 2,
  }

  #endregion

}

#endregion Designer generated code
