// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: ENGOJBOMDAF.proto
// </auto-generated>
#pragma warning disable 1591, 0612, 3021, 8981
#region Designer generated code

using pb = global::Google.Protobuf;
using pbc = global::Google.Protobuf.Collections;
using pbr = global::Google.Protobuf.Reflection;
using scg = global::System.Collections.Generic;
namespace March7thHoney.Proto {

  /// <summary>Holder for reflection information generated from ENGOJBOMDAF.proto</summary>
  public static partial class ENGOJBOMDAFReflection {

    #region Descriptor
    /// <summary>File descriptor for ENGOJBOMDAF.proto</summary>
    public static pbr::FileDescriptor Descriptor {
      get { return descriptor; }
    }
    private static pbr::FileDescriptor descriptor;

    static ENGOJBOMDAFReflection() {
      byte[] descriptorData = global::System.Convert.FromBase64String(
          string.Concat(
            "ChFFTkdPSkJPTURBRi5wcm90bypHCgtFTkdPSkJPTURBRhIbChdFTkdPSkJP",
            "TURBRl9QQ1BESEVMUEtFTRAAEhsKF0VOR09KQk9NREFGX09BR0FEQ09OSU5D",
            "EAFCFqoCE01hcmNoN3RoSG9uZXkuUHJvdG9iBnByb3RvMw=="));
      descriptor = pbr::FileDescriptor.FromGeneratedCode(descriptorData,
          new pbr::FileDescriptor[] { },
          new pbr::GeneratedClrTypeInfo(new[] {typeof(global::March7thHoney.Proto.ENGOJBOMDAF), }, null, null));
    }
    #endregion

  }
  #region Enums
  public enum ENGOJBOMDAF {
    [pbr::OriginalName("ENGOJBOMDAF_PCPDHELPKEM")] Pcpdhelpkem = 0,
    [pbr::OriginalName("ENGOJBOMDAF_OAGADCONINC")] Oagadconinc = 1,
  }

  #endregion

}

#endregion Designer generated code
