// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: HEAJBHNMJGO.proto
// </auto-generated>
#pragma warning disable 1591, 0612, 3021, 8981
#region Designer generated code

using pb = global::Google.Protobuf;
using pbc = global::Google.Protobuf.Collections;
using pbr = global::Google.Protobuf.Reflection;
using scg = global::System.Collections.Generic;
namespace March7thHoney.Proto {

  /// <summary>Holder for reflection information generated from HEAJBHNMJGO.proto</summary>
  public static partial class HEAJBHNMJGOReflection {

    #region Descriptor
    /// <summary>File descriptor for HEAJBHNMJGO.proto</summary>
    public static pbr::FileDescriptor Descriptor {
      get { return descriptor; }
    }
    private static pbr::FileDescriptor descriptor;

    static HEAJBHNMJGOReflection() {
      byte[] descriptorData = global::System.Convert.FromBase64String(
          string.Concat(
            "ChFIRUFKQkhOTUpHTy5wcm90bypHCgtIRUFKQkhOTUpHTxIbChdIRUFKQkhO",
            "TUpHT19PRkdISktJSE1JQhAAEhsKF0hFQUpCSE5NSkdPX0hGT0ZHSEZOSkxE",
            "EAFCFqoCE01hcmNoN3RoSG9uZXkuUHJvdG9iBnByb3RvMw=="));
      descriptor = pbr::FileDescriptor.FromGeneratedCode(descriptorData,
          new pbr::FileDescriptor[] { },
          new pbr::GeneratedClrTypeInfo(new[] {typeof(global::March7thHoney.Proto.HEAJBHNMJGO), }, null, null));
    }
    #endregion

  }
  #region Enums
  public enum HEAJBHNMJGO {
    [pbr::OriginalName("HEAJBHNMJGO_OFGHJKIHMIB")] Ofghjkihmib = 0,
    [pbr::OriginalName("HEAJBHNMJGO_HFOFGHFNJLD")] Hfofghfnjld = 1,
  }

  #endregion

}

#endregion Designer generated code
