// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: LFGMADFAKHK.proto
// </auto-generated>
#pragma warning disable 1591, 0612, 3021, 8981
#region Designer generated code

using pb = global::Google.Protobuf;
using pbc = global::Google.Protobuf.Collections;
using pbr = global::Google.Protobuf.Reflection;
using scg = global::System.Collections.Generic;
namespace March7thHoney.Proto {

  /// <summary>Holder for reflection information generated from LFGMADFAKHK.proto</summary>
  public static partial class LFGMADFAKHKReflection {

    #region Descriptor
    /// <summary>File descriptor for LFGMADFAKHK.proto</summary>
    public static pbr::FileDescriptor Descriptor {
      get { return descriptor; }
    }
    private static pbr::FileDescriptor descriptor;

    static LFGMADFAKHKReflection() {
      byte[] descriptorData = global::System.Convert.FromBase64String(
          string.Concat(
            "ChFMRkdNQURGQUtISy5wcm90byqBAQoLTEZHTUFERkFLSEsSGwoXTEZHTUFE",
            "RkFLSEtfUENQREhFTFBLRU0QABIbChdMRkdNQURGQUtIS19OTUJDRElMREdO",
            "SxABEhsKF0xGR01BREZBS0hLX0tMSERDT1BQTE5HEAISGwoXTEZHTUFERkFL",
            "SEtfQ0xQSE1BSkpJTEEQA0IWqgITTWFyY2g3dGhIb25leS5Qcm90b2IGcHJv",
            "dG8z"));
      descriptor = pbr::FileDescriptor.FromGeneratedCode(descriptorData,
          new pbr::FileDescriptor[] { },
          new pbr::GeneratedClrTypeInfo(new[] {typeof(global::March7thHoney.Proto.LFGMADFAKHK), }, null, null));
    }
    #endregion

  }
  #region Enums
  public enum LFGMADFAKHK {
    [pbr::OriginalName("LFGMADFAKHK_PCPDHELPKEM")] Pcpdhelpkem = 0,
    [pbr::OriginalName("LFGMADFAKHK_NMBCDILDGNK")] Nmbcdildgnk = 1,
    [pbr::OriginalName("LFGMADFAKHK_KLHDCOPPLNG")] Klhdcopplng = 2,
    [pbr::OriginalName("LFGMADFAKHK_CLPHMAJJILA")] Clphmajjila = 3,
  }

  #endregion

}

#endregion Designer generated code
