// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: LGNEOKBPPEO.proto
// </auto-generated>
#pragma warning disable 1591, 0612, 3021, 8981
#region Designer generated code

using pb = global::Google.Protobuf;
using pbc = global::Google.Protobuf.Collections;
using pbr = global::Google.Protobuf.Reflection;
using scg = global::System.Collections.Generic;
namespace March7thHoney.Proto {

  /// <summary>Holder for reflection information generated from LGNEOKBPPEO.proto</summary>
  public static partial class LGNEOKBPPEOReflection {

    #region Descriptor
    /// <summary>File descriptor for LGNEOKBPPEO.proto</summary>
    public static pbr::FileDescriptor Descriptor {
      get { return descriptor; }
    }
    private static pbr::FileDescriptor descriptor;

    static LGNEOKBPPEOReflection() {
      byte[] descriptorData = global::System.Convert.FromBase64String(
          string.Concat(
            "ChFMR05FT0tCUFBFTy5wcm90byq7AQoLTEdORU9LQlBQRU8SGwoXTEdORU9L",
            "QlBQRU9fUENQREhFTFBLRU0QABIbChdMR05FT0tCUFBFT19HTEVNSEVDTE1H",
            "UBABEhsKF0xHTkVPS0JQUEVPX0pQQUFQTU5LSUVGEAISGwoXTEdORU9LQlBQ",
            "RU9fSkhCSUtDUExGRkoQAxIbChdMR05FT0tCUFBFT19CQ0RIT0ZOTVBORxAE",
            "EhsKF0xHTkVPS0JQUEVPX0NNSEhCUE9IQUhKEAVCFqoCE01hcmNoN3RoSG9u",
            "ZXkuUHJvdG9iBnByb3RvMw=="));
      descriptor = pbr::FileDescriptor.FromGeneratedCode(descriptorData,
          new pbr::FileDescriptor[] { },
          new pbr::GeneratedClrTypeInfo(new[] {typeof(global::March7thHoney.Proto.LGNEOKBPPEO), }, null, null));
    }
    #endregion

  }
  #region Enums
  public enum LGNEOKBPPEO {
    [pbr::OriginalName("LGNEOKBPPEO_PCPDHELPKEM")] Pcpdhelpkem = 0,
    [pbr::OriginalName("LGNEOKBPPEO_GLEMHECLMGP")] Glemheclmgp = 1,
    [pbr::OriginalName("LGNEOKBPPEO_JPAAPMNKIEF")] Jpaapmnkief = 2,
    [pbr::OriginalName("LGNEOKBPPEO_JHBIKCPLFFJ")] Jhbikcplffj = 3,
    [pbr::OriginalName("LGNEOKBPPEO_BCDHOFNMPNG")] Bcdhofnmpng = 4,
    [pbr::OriginalName("LGNEOKBPPEO_CMHHBPOHAHJ")] Cmhhbpohahj = 5,
  }

  #endregion

}

#endregion Designer generated code
