// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: LKBGOMGHGLG.proto
// </auto-generated>
#pragma warning disable 1591, 0612, 3021, 8981
#region Designer generated code

using pb = global::Google.Protobuf;
using pbc = global::Google.Protobuf.Collections;
using pbr = global::Google.Protobuf.Reflection;
using scg = global::System.Collections.Generic;
namespace March7thHoney.Proto {

  /// <summary>Holder for reflection information generated from LKBGOMGHGLG.proto</summary>
  public static partial class LKBGOMGHGLGReflection {

    #region Descriptor
    /// <summary>File descriptor for LKBGOMGHGLG.proto</summary>
    public static pbr::FileDescriptor Descriptor {
      get { return descriptor; }
    }
    private static pbr::FileDescriptor descriptor;

    static LKBGOMGHGLGReflection() {
      byte[] descriptorData = global::System.Convert.FromBase64String(
          string.Concat(
            "ChFMS0JHT01HSEdMRy5wcm90bypkCgtMS0JHT01HSEdMRxIbChdMS0JHT01H",
            "SEdMR19KRElOUElPSElFSRAAEhsKF0xLQkdPTUdIR0xHX0hMUERPSkJJT0lK",
            "EAESGwoXTEtCR09NR0hHTEdfREtCT0dBSUJLQkQQAkIWqgITTWFyY2g3dGhI",
            "b25leS5Qcm90b2IGcHJvdG8z"));
      descriptor = pbr::FileDescriptor.FromGeneratedCode(descriptorData,
          new pbr::FileDescriptor[] { },
          new pbr::GeneratedClrTypeInfo(new[] {typeof(global::March7thHoney.Proto.LKBGOMGHGLG), }, null, null));
    }
    #endregion

  }
  #region Enums
  public enum LKBGOMGHGLG {
    [pbr::OriginalName("LKBGOMGHGLG_JDINPIOHIEI")] Jdinpiohiei = 0,
    [pbr::OriginalName("LKBGOMGHGLG_HLPDOJBIOIJ")] Hlpdojbioij = 1,
    [pbr::OriginalName("LKBGOMGHGLG_DKBOGAIBKBD")] Dkbogaibkbd = 2,
  }

  #endregion

}

#endregion Designer generated code
