// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: OCLEJLEFBFO.proto
// </auto-generated>
#pragma warning disable 1591, 0612, 3021, 8981
#region Designer generated code

using pb = global::Google.Protobuf;
using pbc = global::Google.Protobuf.Collections;
using pbr = global::Google.Protobuf.Reflection;
using scg = global::System.Collections.Generic;
namespace March7thHoney.Proto {

  /// <summary>Holder for reflection information generated from OCLEJLEFBFO.proto</summary>
  public static partial class OCLEJLEFBFOReflection {

    #region Descriptor
    /// <summary>File descriptor for OCLEJLEFBFO.proto</summary>
    public static pbr::FileDescriptor Descriptor {
      get { return descriptor; }
    }
    private static pbr::FileDescriptor descriptor;

    static OCLEJLEFBFOReflection() {
      byte[] descriptorData = global::System.Convert.FromBase64String(
          string.Concat(
            "ChFPQ0xFSkxFRkJGTy5wcm90bypHCgtPQ0xFSkxFRkJGTxIbChdPQ0xFSkxF",
            "RkJGT19QQ1BESEVMUEtFTRAAEhsKF09DTEVKTEVGQkZPX0ZGT0tKT0lFQ0pG",
            "EAFCFqoCE01hcmNoN3RoSG9uZXkuUHJvdG9iBnByb3RvMw=="));
      descriptor = pbr::FileDescriptor.FromGeneratedCode(descriptorData,
          new pbr::FileDescriptor[] { },
          new pbr::GeneratedClrTypeInfo(new[] {typeof(global::March7thHoney.Proto.OCLEJLEFBFO), }, null, null));
    }
    #endregion

  }
  #region Enums
  public enum OCLEJLEFBFO {
    [pbr::OriginalName("OCLEJLEFBFO_PCPDHELPKEM")] Pcpdhelpkem = 0,
    [pbr::OriginalName("OCLEJLEFBFO_FFOKJOIECJF")] Ffokjoiecjf = 1,
  }

  #endregion

}

#endregion Designer generated code
