// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: OOCEFDIBHNP.proto
// </auto-generated>
#pragma warning disable 1591, 0612, 3021, 8981
#region Designer generated code

using pb = global::Google.Protobuf;
using pbc = global::Google.Protobuf.Collections;
using pbr = global::Google.Protobuf.Reflection;
using scg = global::System.Collections.Generic;
namespace March7thHoney.Proto {

  /// <summary>Holder for reflection information generated from OOCEFDIBHNP.proto</summary>
  public static partial class OOCEFDIBHNPReflection {

    #region Descriptor
    /// <summary>File descriptor for OOCEFDIBHNP.proto</summary>
    public static pbr::FileDescriptor Descriptor {
      get { return descriptor; }
    }
    private static pbr::FileDescriptor descriptor;

    static OOCEFDIBHNPReflection() {
      byte[] descriptorData = global::System.Convert.FromBase64String(
          string.Concat(
            "ChFPT0NFRkRJQkhOUC5wcm90bypkCgtPT0NFRkRJQkhOUBIbChdPT0NFRkRJ",
            "QkhOUF9QQ1BESEVMUEtFTRAAEhsKF09PQ0VGRElCSE5QX0xFREVFQUhDREtJ",
            "EAESGwoXT09DRUZESUJITlBfSENFS0ZFRU5OQ0EQAkIWqgITTWFyY2g3dGhI",
            "b25leS5Qcm90b2IGcHJvdG8z"));
      descriptor = pbr::FileDescriptor.FromGeneratedCode(descriptorData,
          new pbr::FileDescriptor[] { },
          new pbr::GeneratedClrTypeInfo(new[] {typeof(global::March7thHoney.Proto.OOCEFDIBHNP), }, null, null));
    }
    #endregion

  }
  #region Enums
  public enum OOCEFDIBHNP {
    [pbr::OriginalName("OOCEFDIBHNP_PCPDHELPKEM")] Pcpdhelpkem = 0,
    [pbr::OriginalName("OOCEFDIBHNP_LEDEEAHCDKI")] Ledeeahcdki = 1,
    [pbr::OriginalName("OOCEFDIBHNP_HCEKFEENNCA")] Hcekfeennca = 2,
  }

  #endregion

}

#endregion Designer generated code
