// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: RelicDiscardType.proto
// </auto-generated>
#pragma warning disable 1591, 0612, 3021, 8981
#region Designer generated code

using pb = global::Google.Protobuf;
using pbc = global::Google.Protobuf.Collections;
using pbr = global::Google.Protobuf.Reflection;
using scg = global::System.Collections.Generic;
namespace March7thHoney.Proto {

  /// <summary>Holder for reflection information generated from RelicDiscardType.proto</summary>
  public static partial class RelicDiscardTypeReflection {

    #region Descriptor
    /// <summary>File descriptor for RelicDiscardType.proto</summary>
    public static pbr::FileDescriptor Descriptor {
      get { return descriptor; }
    }
    private static pbr::FileDescriptor descriptor;

    static RelicDiscardTypeReflection() {
      byte[] descriptorData = global::System.Convert.FromBase64String(
          string.Concat(
            "ChZSZWxpY0Rpc2NhcmRUeXBlLnByb3RvKmkKEFJlbGljRGlzY2FyZFR5cGUS",
            "GwoXRUdFSkdOQURPSEdfSUZQRExDT0lFTkYQABIbChdFR0VKR05BRE9IR19M",
            "Qk9PQkhBTU5CSxABEhsKF0VHRUpHTkFET0hHX1BCS0dGRkNOQkJIEAJCFqoC",
            "E01hcmNoN3RoSG9uZXkuUHJvdG9iBnByb3RvMw=="));
      descriptor = pbr::FileDescriptor.FromGeneratedCode(descriptorData,
          new pbr::FileDescriptor[] { },
          new pbr::GeneratedClrTypeInfo(new[] {typeof(global::March7thHoney.Proto.RelicDiscardType), }, null, null));
    }
    #endregion

  }
  #region Enums
  public enum RelicDiscardType {
    [pbr::OriginalName("EGEJGNADOHG_IFPDLCOIENF")] EgejgnadohgIfpdlcoienf = 0,
    [pbr::OriginalName("EGEJGNADOHG_LBOOBHAMNBK")] EgejgnadohgLboobhamnbk = 1,
    [pbr::OriginalName("EGEJGNADOHG_PBKGFFCNBBH")] EgejgnadohgPbkgffcnbbh = 2,
  }

  #endregion

}

#endregion Designer generated code
