using Google.Protobuf.Reflection;

namespace March7thHoney.Proto;

public enum GridFightUpdateSrcType
{
	[OriginalName("LNPFEFKJDHP_HEFEPINLBDP")]
	LnpfefkjdhpHefepinlbdp,
	[OriginalName("LNPFEFKJDHP_OOPNBCIJHMP")]
	LnpfefkjdhpOopnbcijhmp,
	[OriginalName("LNPFEFKJDHP_BJDEAAHIBGE")]
	LnpfefkjdhpBjdeaahibge,
	[OriginalName("LNPFEFKJDHP_HNDKHMEFAAL")]
	LnpfefkjdhpHndkhmefaal,
	[OriginalName("LNPFEFKJDHP_KCEFFLKABGH")]
	LnpfefkjdhpKcefflkabgh,
	[OriginalName("LNPFEFKJDHP_PPDDODGLNLH")]
	LnpfefkjdhpPpddodglnlh,
	[OriginalName("LNPFEFKJDHP_MDEKNJIEAPJ")]
	LnpfefkjdhpMdeknjieapj,
	[OriginalName("LNPFEFKJDHP_EJKEJDNHIOE")]
	LnpfefkjdhpEjkejdnhioe,
	[OriginalName("LNPFEFKJDHP_DPEKJIIICGH")]
	LnpfefkjdhpDpekjiiicgh,
	[OriginalName("LNPFEFKJDHP_GKNDLFBPADH")]
	LnpfefkjdhpGkndlfbpadh,
	[OriginalName("LNPFEFKJDHP_LFNKHCBHMPD")]
	LnpfefkjdhpLfnkhcbhmpd,
	[OriginalName("LNPFEFKJDHP_KKPBAGFHPBB")]
	LnpfefkjdhpKkpbagfhpbb,
	[OriginalName("LNPFEFKJDHP_MHNCGOEHMCH")]
	LnpfefkjdhpMhncgoehmch,
	[OriginalName("LNPFEFKJDHP_DGOJIHIJLAF")]
	LnpfefkjdhpDgojihijlaf,
	[OriginalName("LNPFEFKJDHP_HCAFEEDHILF")]
	LnpfefkjdhpHcafeedhilf,
	[OriginalName("LNPFEFKJDHP_PDJHDFKOCKK")]
	LnpfefkjdhpPdjhdfkockk,
	[OriginalName("LNPFEFKJDHP_HICGJMGBCPG")]
	LnpfefkjdhpHicgjmgbcpg,
	[OriginalName("LNPFEFKJDHP_FKFKLEFKBBM")]
	LnpfefkjdhpFkfklefkbbm,
	[OriginalName("LNPFEFKJDHP_JALHDINECFE")]
	LnpfefkjdhpJalhdinecfe,
	[OriginalName("LNPFEFKJDHP_KHOAIFIFGDJ")]
	LnpfefkjdhpKhoaififgdj,
	[OriginalName("LNPFEFKJDHP_JIDJJPJKLFH")]
	LnpfefkjdhpJidjjpjklfh,
	[OriginalName("LNPFEFKJDHP_NGJHPBMCCPC")]
	LnpfefkjdhpNgjhpbmccpc,
	[OriginalName("LNPFEFKJDHP_EEAOKENAFKH")]
	LnpfefkjdhpEeaokenafkh,
	[OriginalName("LNPFEFKJDHP_GLEMBDJFLAF")]
	LnpfefkjdhpGlembdjflaf,
	[OriginalName("LNPFEFKJDHP_PNEJELGGLEJ")]
	LnpfefkjdhpPnejelgglej,
	[OriginalName("LNPFEFKJDHP_PPBJJOFFNJK")]
	LnpfefkjdhpPpbjjoffnjk,
	[OriginalName("LNPFEFKJDHP_NEFKFLKAMPO")]
	LnpfefkjdhpNefkflkampo,
	[OriginalName("LNPFEFKJDHP_DKGFLMNEINA")]
	LnpfefkjdhpDkgflmneina,
	[OriginalName("LNPFEFKJDHP_IFANONDMOBE")]
	LnpfefkjdhpIfanondmobe,
	[OriginalName("LNPFEFKJDHP_PFIFEJDCMOJ")]
	LnpfefkjdhpPfifejdcmoj,
	[OriginalName("LNPFEFKJDHP_ODJDFIHICLK")]
	LnpfefkjdhpOdjdfihiclk,
	[OriginalName("LNPFEFKJDHP_NGHOFPNIGAC")]
	LnpfefkjdhpNghofpnigac,
	[OriginalName("LNPFEFKJDHP_AJDDCALIKLH")]
	LnpfefkjdhpAjddcaliklh,
	[OriginalName("LNPFEFKJDHP_PJFMPKCAHAA")]
	LnpfefkjdhpPjfmpkcahaa
}
