using System;
using Google.Protobuf.Reflection;

namespace March7thHoney.Proto;

public static class DFAGKMFOENBReflection
{
	private static FileDescriptor descriptor;

	public static FileDescriptor Descriptor => descriptor;

	static DFAGKMFOENBReflection()
	{
		_003C_003Ey__InlineArray52<string> buffer = default(_003C_003Ey__InlineArray52<string>);
		buffer[0] = "ChFERkFHS01GT0VOQi5wcm90bxoRQUJBQkhLQUdIRUoucHJvdG8aEUFDRkdK";
		buffer[1] = "Qk5NRkRDLnByb3RvGhFCQktBUERDRUNETi5wcm90bxoRQ0FFSU5MSklCUEIu";
		buffer[2] = "cHJvdG8aEUNGUEtLRU1LS1BPLnByb3RvGhFDR05DR0ZCQ05IUC5wcm90bxoR";
		buffer[3] = "REVFQ0ZDQUxNRk4ucHJvdG8aEURFRUxKS0hETERILnByb3RvGhFETUxGTkdF";
		buffer[4] = "Sk9IQy5wcm90bxoRRE9HR0lETklOSlAucHJvdG8aEUVDSUlMUExOUEhKLnBy";
		buffer[5] = "b3RvGhFFRUlPSURHSkNJTC5wcm90bxoRRkRITU5FSkJPRUIucHJvdG8aEUZJ";
		buffer[6] = "TElGQ0NOQVBILnByb3RvGhFGSklJUEZDTUpDSi5wcm90bxoRRk5NR0RMRExN";
		buffer[7] = "TEoucHJvdG8aEUdDRUJGSkVFRk9MLnByb3RvGhFHRU1BSUdORE5QSy5wcm90";
		buffer[8] = "bxoRR05CS0tQT0xMQUEucHJvdG8aEUdQRUpHUEpORUNGLnByb3RvGhFISkdG";
		buffer[9] = "RElLRElITy5wcm90bxoRSE9NTlBDSkVDQkgucHJvdG8aEUhPUEtJT0tHRUJQ";
		buffer[10] = "LnByb3RvGhFKQUVPQUdOS05CTC5wcm90bxoRSkNGRUVOTk5DQkwucHJvdG8a";
		buffer[11] = "EUpDSUpIQ0ZCR0tHLnByb3RvGhFLSEhIRkhFT0RFRC5wcm90bxoRTUlJT0xJ";
		buffer[12] = "SU9HSUcucHJvdG8aEU5CREJOREVBUE1OLnByb3RvGhFOQ0ZLSExOSE1BSi5w";
		buffer[13] = "cm90bxoRT0VNTkhHTVBNUEQucHJvdG8aEU9GQUZEUEdDRVBPLnByb3RvGhFP";
		buffer[14] = "SEhLR0hFR0pPRy5wcm90bxoRUEFGT09PSUtGT0YucHJvdG8aEVBERUhETkFP";
		buffer[15] = "S0JDLnByb3RvGhFQR01DSkxCTk5MRi5wcm90byKtDAoLREZBR0tNRk9FTkIS";
		buffer[16] = "IwoLTE1JSUNFTk1PQkkYCCABKAsyDC5QQUZPT09JS0ZPRkgAEiMKC1BKRktK";
		buffer[17] = "SExBQVBGGA4gASgLMgwuUEFGT09PSUtGT0ZIABIjCgtPQU1QSEJITk5CSxgg";
		buffer[18] = "IAEoCzIMLkFCQUJIS0FHSEVKSAASIwoLQURFSE1MRUlDSEwYJCABKAsyDC5G";
		buffer[19] = "SklJUEZDTUpDSkgAEiMKC05FSE9NT0JCUEVOGCkgASgLMgwuRk5NR0RMRExN";
		buffer[20] = "TEpIABIkCgtBT0dNUEFKQkZCSBjVASABKAsyDC5ISkdGRElLRElIT0gAEiQK";
		buffer[21] = "C0FITE1JQ0tMR0hQGNcBIAEoCzIMLktISEhGSEVPREVESAASJAoLQUlGSlBO";
		buffer[22] = "RE1BQ0kYoQIgASgLMgwuRkRITU5FSkJPRUJIABIkCgtCR0hNRk9NTUxPSBij";
		buffer[23] = "AiABKAsyDC5OQkRCTkRFQVBNTkgAEiQKC1BNR0NHSUdQTkZHGKYCIAEoCzIM";
		buffer[24] = "LktISEhGSEVPREVESAASJAoLTkZQS0ZGQ0hMSEYYrQIgASgLMgwuQ0ZQS0tF";
		buffer[25] = "TUtLUE9IABIkCgtISFBNSk5LTktIThiuAiABKAsyDC5FQ0lJTFBMTlBISkgA";
		buffer[26] = "EiQKC05HR0FESk9PTUVLGJADIAEoCzIMLk9ISEtHSEVHSk9HSAASJAoLTk1F";
		buffer[27] = "TE9DSk5PQVAYuAMgASgLMgwuQ0dOQ0dGQkNOSFBIABIkCgtGQkZITUtDRkJQ";
		buffer[28] = "RBjIAyABKAsyDC5PRU1OSEdNUE1QREgAEiQKC0xQSUxNT0VDUExBGNUDIAEo";
		buffer[29] = "CzIMLk9GQUZEUEdDRVBPSAASJAoLS0VDQkxPSEVOS08Y3QMgASgLMgwuRUVJ";
		buffer[30] = "T0lER0pDSUxIABIkCgtFR0tPSUpIS05GRRjzAyABKAsyDC5IT1BLSU9LR0VC";
		buffer[31] = "UEgAEiQKC0FBQ09BQkJKSEtPGNgEIAEoCzIMLk5DRktITE5ITUFKSAASJAoL";
		buffer[32] = "UEtJTkxHQlBIQlAY8wUgASgLMgwuTUlJT0xJSU9HSUdIABIkCgtPTUZCSlBE";
		buffer[33] = "RkRCShiWBiABKAsyDC5HQ0VCRkpFRUZPTEgAEiQKC0FGRU5BSUJOS0dJGKMG";
		buffer[34] = "IAEoCzIMLkhPTU5QQ0pFQ0JISAASJAoLRUlNQUZQRUJDQUUY7QYgASgLMgwu";
		buffer[35] = "RE1MRk5HRUpPSENIABIkCgtDRUZHT01GTkhHTxjkByABKAsyDC5ERUVMSktI";
		buffer[36] = "RExESEgAEiQKC0pFRUtFSUdNREpOGMcIIAEoCzIMLktISEhGSEVPREVESAAS";
		buffer[37] = "JAoLS0lJREJMRkxBSk4YyQggASgLMgwuQ0FFSU5MSklCUEJIABIkCgtHQUZF";
		buffer[38] = "TkZDR0lGSxiBCSABKAsyDC5ERUVDRkNBTE1GTkgAEiQKC0pOS0ZFR0hDQUJL";
		buffer[39] = "GMYJIAEoCzIMLkpDSUpIQ0ZCR0tHSAASJAoLTURHSkhCSlBESkgY6QkgASgL";
		buffer[40] = "MgwuSkFFT0FHTktOQkxIABIkCgtJTUpOSkZDQ0pQQxiMCiABKAsyDC5HRU1B";
		buffer[41] = "SUdORE5QS0gAEiQKC0hOTEFFSUJERkpNGI4KIAEoCzIMLkhKR0ZESUtESUhP";
		buffer[42] = "SAASJAoLR0VFTUNMQ0NGQ04YnQogASgLMgwuR1BFSkdQSk5FQ0ZIABIkCgtJ";
		buffer[43] = "RENHS09NQURQTBixCyABKAsyDC5QR01DSkxCTk5MRkgAEiQKC0NPSUtFTENO";
		buffer[44] = "SUlQGNQLIAEoCzIMLkFDRkdKQk5NRkRDSAASJAoLRUlPS09BREVPRkMYrAwg";
		buffer[45] = "ASgLMgwuRE9HR0lETklOSlBIABIkCgtIUEdFRElBR0NMSRi8DCABKAsyDC5Q";
		buffer[46] = "REVIRE5BT0tCQ0gAEiQKC0FHS0dNTE9NREdFGNsMIAEoCzIMLkJCS0FQRENF";
		buffer[47] = "Q0ROSAASJAoLTktMQ0VITkZDS00Y8gwgASgLMgwuUERFSEROQU9LQkNIABIk";
		buffer[48] = "CgtCSkNGUEJEQ0NCRxjFDSABKAsyDC5GSUxJRkNDTkFQSEgAEiQKC09NS0xM";
		buffer[49] = "UEZQQUJMGKMPIAEoCzIMLkpDRkVFTk5OQ0JMSAASJAoLTkhMQ1BETU9GTEEY";
		buffer[50] = "rQ8gASgLMgwuR05CS0tQT0xMQUFIAEINCgtCUElIRkFKQ0xPQ0IWqgITTWFy";
		buffer[51] = "Y2g3dGhIb25leS5Qcm90b2IGcHJvdG8z";
		descriptor = FileDescriptor.FromGeneratedCode(Convert.FromBase64String(string.Concat((ReadOnlySpan<string?>)buffer)), new FileDescriptor[36]
		{
			ABABHKAGHEJReflection.Descriptor,
			ACFGJBNMFDCReflection.Descriptor,
			BBKAPDCECDNReflection.Descriptor,
			CAEINLJIBPBReflection.Descriptor,
			CFPKKEMKKPOReflection.Descriptor,
			CGNCGFBCNHPReflection.Descriptor,
			DEECFCALMFNReflection.Descriptor,
			DEELJKHDLDHReflection.Descriptor,
			DMLFNGEJOHCReflection.Descriptor,
			DOGGIDNINJPReflection.Descriptor,
			ECIILPLNPHJReflection.Descriptor,
			EEIOIDGJCILReflection.Descriptor,
			FDHMNEJBOEBReflection.Descriptor,
			FILIFCCNAPHReflection.Descriptor,
			FJIIPFCMJCJReflection.Descriptor,
			FNMGDLDLMLJReflection.Descriptor,
			GCEBFJEEFOLReflection.Descriptor,
			GEMAIGNDNPKReflection.Descriptor,
			GNBKKPOLLAAReflection.Descriptor,
			GPEJGPJNECFReflection.Descriptor,
			HJGFDIKDIHOReflection.Descriptor,
			HOMNPCJECBHReflection.Descriptor,
			HOPKIOKGEBPReflection.Descriptor,
			JAEOAGNKNBLReflection.Descriptor,
			JCFEENNNCBLReflection.Descriptor,
			JCIJHCFBGKGReflection.Descriptor,
			KHHHFHEODEDReflection.Descriptor,
			MIIOLIIOGIGReflection.Descriptor,
			NBDBNDEAPMNReflection.Descriptor,
			NCFKHLNHMAJReflection.Descriptor,
			OEMNHGMPMPDReflection.Descriptor,
			OFAFDPGCEPOReflection.Descriptor,
			OHHKGHEGJOGReflection.Descriptor,
			PAFOOOIKFOFReflection.Descriptor,
			PDEHDNAOKBCReflection.Descriptor,
			PGMCJLBNNLFReflection.Descriptor
		}, new GeneratedClrTypeInfo(null, null, new GeneratedClrTypeInfo[1]
		{
			new GeneratedClrTypeInfo(typeof(DFAGKMFOENB), DFAGKMFOENB.Parser, new string[41]
			{
				"LMIICENMOBI", "PJFKJHLAAPF", "OAMPHBHNNBK", "ADEHMLEICHL", "NEHOMOBBPEN", "AOGMPAJBFBH", "AHLMICKLGHP", "AIFJPNDMACI", "BGHMFOMMLOH", "PMGCGIGPNFG",
				"NFPKFFCHLHF", "HHPMJNKNKHN", "NGGADJOOMEK", "NMELOCJNOAP", "FBFHMKCFBPD", "LPILMOECPLA", "KECBLOHENKO", "EGKOIJHKNFE", "AACOABBJHKO", "PKINLGBPHBP",
				"OMFBJPDFDBJ", "AFENAIBNKGI", "EIMAFPEBCAE", "CEFGOMFNHGO", "JEEKEIGMDJN", "KIIDBLFLAJN", "GAFENFCGIFK", "JNKFEGHCABK", "MDGJHBJPDJH", "IMJNJFCCJPC",
				"HNLAEIBDFJM", "GEEMCLCCFCN", "IDCGKOMADPL", "COIKELCNIIP", "EIOKOADEOFC", "HPGEDIAGCLI", "AGKGMLOMDGE", "NKLCEHNFCKM", "BJCFPBDCCBG", "OMKLLPFPABL",
				"NHLCPDMOFLA"
			}, new string[1] { "BPIHFAJCLOC" }, null, null, null)
		}));
	}
}
