using System;
using Google.Protobuf.Reflection;

namespace March7thHoney.Proto;

public static class SelectRogueBonusReqReflection
{
	private static FileDescriptor descriptor;

	public static FileDescriptor Descriptor => descriptor;

	static SelectRogueBonusReqReflection()
	{
		_003C_003Ey__InlineArray51<string> buffer = default(_003C_003Ey__InlineArray51<string>);
		buffer[0] = "ChlTZWxlY3RSb2d1ZUJvbnVzUmVxLnByb3RvGhFBTEhHQ0JQSkxNTy5wcm90";
		buffer[1] = "bxoRQU5CUE1KSFBMT1AucHJvdG8aEUJBQU1FSk5NTU9CLnByb3RvGhFCQ01M";
		buffer[2] = "REtLSUlLQS5wcm90bxoRQkRHRkVHUEhLS08ucHJvdG8aEUJJQUdMT0tCQk1J";
		buffer[3] = "LnByb3RvGhFCSUVMQUFNRVBESy5wcm90bxoRREVPRU9KQkxJQlAucHJvdG8a";
		buffer[4] = "EURHQ01KTk5IRkdQLnByb3RvGhFET0FEQkJPRkJKQS5wcm90bxoRRUNHRUZE";
		buffer[5] = "S0JDQ0IucHJvdG8aEUVLRE1ETkVLQU1OLnByb3RvGhFFT0JIS01HSkdQRy5w";
		buffer[6] = "cm90bxoRRkZHTUhMQ0VBT00ucHJvdG8aEUZOREJGT0lQUEZLLnByb3RvGhFG";
		buffer[7] = "UExDSEJOTkFIRC5wcm90bxoRR1BMUENKS0xJSUgucHJvdG8aEUhHQ0lESEJJ";
		buffer[8] = "TEFDLnByb3RvGhFISUxDTktJTkVJQS5wcm90bxoRSE1JSEpJTUNJRUEucHJv";
		buffer[9] = "dG8aEUlCTEhQT0JPT1BFLnByb3RvGhFJRExMS0hIQklJRC5wcm90bxoRSUVN";
		buffer[10] = "T01MRkFBSUUucHJvdG8aEUlGTEhFTE9MREtBLnByb3RvGhFKQUlFTENJQUtB";
		buffer[11] = "Ti5wcm90bxoRSklGT1BCTk5LT04ucHJvdG8aEUtNREJNTEFJQ0xCLnByb3Rv";
		buffer[12] = "GhFMR0RBUEFCS0FMSC5wcm90bxoRTUpLRU9CT01BR1AucHJvdG8aEU1KUEdM";
		buffer[13] = "QUZOSkFCLnByb3RvGhFNS1BPSEtPUEFQRS5wcm90bxoRT0ZMTkxKRUxKRU0u";
		buffer[14] = "cHJvdG8aEU9QUE5BSExQQUZHLnByb3RvGhFQQVBIRkdQTkNJSi5wcm90byKq";
		buffer[15] = "DAoTU2VsZWN0Um9ndWVCb251c1JlcRITCgtNSlBDQkVBQUFCShgMIAEoDRIj";
		buffer[16] = "CgtNQkJLSENKTUdHTBgeIAEoCzIMLkhJTENOS0lORUlBSAASJAoLUENORUpK";
		buffer[17] = "QkRFTEMYqwEgASgLMgwuSE1JSEpJTUNJRUFIABIkCgtJTEFLT09QRU9EUBiB";
		buffer[18] = "AiABKAsyDC5JRU1PTUxGQUFJRUgAEiQKC0xDRE9PSEhOQ09EGJQCIAEoCzIM";
		buffer[19] = "LkRPQURCQk9GQkpBSAASJAoLSkNFSFBQUENJUE4YsgIgASgLMgwuTUpQR0xB";
		buffer[20] = "Rk5KQUJIABIkCgtESkZKS0JCQUdFTxi2AiABKAsyDC5NS1BPSEtPUEFQRUgA";
		buffer[21] = "EiQKC0NMTExGSURJTklNGL4CIAEoCzIMLkJJQUdMT0tCQk1JSAASJAoLQkVN";
		buffer[22] = "T0VMQ0lCQUkY7gIgASgLMgwuSkFJRUxDSUFLQU5IABIkCgtJSUNLT0pKQURO";
		buffer[23] = "SBjzAiABKAsyDC5ISUxDTktJTkVJQUgAEiQKC1BPTk1BSEVJSE1KGJUDIAEo";
		buffer[24] = "CzIMLklETExLSEhCSUlESAASJAoLTUlQRUdKTk1FRUoYngQgASgLMgwuREVP";
		buffer[25] = "RU9KQkxJQlBIABIkCgtQREdDTEdMT0ZLSxjLBCABKAsyDC5CREdGRUdQSEtL";
		buffer[26] = "T0gAEiQKC0xJTUVGS0RIT0xEGLAFIAEoCzIMLkVLRE1ETkVLQU1OSAASJAoL";
		buffer[27] = "SEpQSUtMQUxLT0QYmgYgASgLMgwuT1BQTkFITFBBRkdIABIkCgtKUEFOUE5O";
		buffer[28] = "TU9PRhicBiABKAsyDC5NSktFT0JPTUFHUEgAEiQKC0dDS0REQkhJSERCGLgG";
		buffer[29] = "IAEoCzIMLkJER0ZFR1BIS0tPSAASJAoLSENHTkFITkpDSEEY0gYgASgLMgwu";
		buffer[30] = "SUZMSEVMT0xES0FIABIkCgtGTElLRUFLUEtKQxjiBiABKAsyDC5ISUxDTktJ";
		buffer[31] = "TkVJQUgAEiQKC1BGS0JBREROR0RMGMAHIAEoCzIMLkRHQ01KTk5IRkdQSAAS";
		buffer[32] = "JAoLSUFDSUFKR0JPT08YyQcgASgLMgwuQklFTEFBTUVQREtIABIkCgtBRUlN";
		buffer[33] = "SkNHQ1BMSBjkByABKAsyDC5KSUZPUEJOTktPTkgAEiQKC1BKTUNBRUFGSUtI";
		buffer[34] = "GL4IIAEoCzIMLlBBUEhGR1BOQ0lKSAASJAoLQ0tBQUNOTE9JQU8Y8AggASgL";
		buffer[35] = "MgwuRkZHTUhMQ0VBT01IABIkCgtQTklPR0dOSE1PQRj1CSABKAsyDC5FT0JI";
		buffer[36] = "S01HSkdQR0gAEiQKC0tFRkdPTEhLQ0RCGK4KIAEoCzIMLkZQTENIQk5OQUhE";
		buffer[37] = "SAASJAoLSkVOQkdNT0VBSEkYswogASgLMgwuRkZHTUhMQ0VBT01IABIkCgtF";
		buffer[38] = "QkJER0FMTUJKSRjWCiABKAsyDC5BTkJQTUpIUExPUEgAEiQKC0pCUEpBTEJP";
		buffer[39] = "RUFQGJoLIAEoCzIMLkxHREFQQUJLQUxISAASJAoLR0pGUEVJRkhISEQYmAwg";
		buffer[40] = "ASgLMgwuSEdDSURIQklMQUNIABIkCgtFR0JETERLSEVNRxizDCABKAsyDC5B";
		buffer[41] = "TEhHQ0JQSkxNT0gAEiQKC0FBRExGSkRFTUpNGMIMIAEoCzIMLkhJTENOS0lO";
		buffer[42] = "RUlBSAASJAoLSk9NS09ORkZDS0gY0QwgASgLMgwuQkFBTUVKTk1NT0JIABIk";
		buffer[43] = "CgtKQ1BKSExJQ0hGShiGDSABKAsyDC5LTURCTUxBSUNMQkgAEiQKC0dKREVD";
		buffer[44] = "QkxBSkRNGJ8NIAEoCzIMLkVDR0VGREtCQ0NCSAASJAoLSE9GSU9CS0lNR1AY";
		buffer[45] = "mA4gASgLMgwuQkNNTERLS0lJS0FIABIkCgtFTVBITkRFSkdDTBjtDiABKAsy";
		buffer[46] = "DC5GTkRCRk9JUFBGS0gAEiQKC0VPREZIUERMRk5PGK4PIAEoCzIMLkdQTFBD";
		buffer[47] = "SktMSUlISAASJAoLUEpOREJLTUZJS0gYsw8gASgLMgwuQkRHRkVHUEhLS09I";
		buffer[48] = "ABIlCgtKSkZHRUpGRkNDQxjGuQIgASgLMgwuT0ZMTkxKRUxKRU1IABIlCgtN";
		buffer[49] = "Qk1ET0pGQkFKThj2zAYgASgLMgwuSUJMSFBPQk9PUEVIAEINCgtCUElIRkFK";
		buffer[50] = "Q0xPQ0IWqgITTWFyY2g3dGhIb25leS5Qcm90b2IGcHJvdG8z";
		descriptor = FileDescriptor.FromGeneratedCode(Convert.FromBase64String(string.Concat((ReadOnlySpan<string?>)buffer)), new FileDescriptor[34]
		{
			ALHGCBPJLMOReflection.Descriptor,
			ANBPMJHPLOPReflection.Descriptor,
			BAAMEJNMMOBReflection.Descriptor,
			BCMLDKKIIKAReflection.Descriptor,
			BDGFEGPHKKOReflection.Descriptor,
			BIAGLOKBBMIReflection.Descriptor,
			BIELAAMEPDKReflection.Descriptor,
			DEOEOJBLIBPReflection.Descriptor,
			DGCMJNNHFGPReflection.Descriptor,
			DOADBBOFBJAReflection.Descriptor,
			ECGEFDKBCCBReflection.Descriptor,
			EKDMDNEKAMNReflection.Descriptor,
			EOBHKMGJGPGReflection.Descriptor,
			FFGMHLCEAOMReflection.Descriptor,
			FNDBFOIPPFKReflection.Descriptor,
			FPLCHBNNAHDReflection.Descriptor,
			GPLPCJKLIIHReflection.Descriptor,
			HGCIDHBILACReflection.Descriptor,
			HILCNKINEIAReflection.Descriptor,
			HMIHJIMCIEAReflection.Descriptor,
			IBLHPOBOOPEReflection.Descriptor,
			IDLLKHHBIIDReflection.Descriptor,
			IEMOMLFAAIEReflection.Descriptor,
			IFLHELOLDKAReflection.Descriptor,
			JAIELCIAKANReflection.Descriptor,
			JIFOPBNNKONReflection.Descriptor,
			KMDBMLAICLBReflection.Descriptor,
			LGDAPABKALHReflection.Descriptor,
			MJKEOBOMAGPReflection.Descriptor,
			MJPGLAFNJABReflection.Descriptor,
			MKPOHKOPAPEReflection.Descriptor,
			OFLNLJELJEMReflection.Descriptor,
			OPPNAHLPAFGReflection.Descriptor,
			PAPHFGPNCIJReflection.Descriptor
		}, new GeneratedClrTypeInfo(null, null, new GeneratedClrTypeInfo[1]
		{
			new GeneratedClrTypeInfo(typeof(SelectRogueBonusReq), SelectRogueBonusReq.Parser, new string[41]
			{
				"MJPCBEAAABJ", "MBBKHCJMGGL", "PCNEJJBDELC", "ILAKOOPEODP", "LCDOOHHNCOD", "JCEHPPPCIPN", "DJFJKBBAGEO", "CLLLFIDINIM", "BEMOELCIBAI", "IICKOJJADNH",
				"PONMAHEIHMJ", "MIPEGJNMEEJ", "PDGCLGLOFKK", "LIMEFKDHOLD", "HJPIKLALKOD", "JPANPNNMOOF", "GCKDDBHIHDB", "HCGNAHNJCHA", "FLIKEAKPKJC", "PFKBADDNGDL",
				"IACIAJGBOOO", "AEIMJCGCPLH", "PJMCAEAFIKH", "CKAACNLOIAO", "PNIOGGNHMOA", "KEFGOLHKCDB", "JENBGMOEAHI", "EBBDGALMBJI", "JBPJALBOEAP", "GJFPEIFHHHD",
				"EGBDLDKHEMG", "AADLFJDEMJM", "JOMKONFFCKH", "JCPJHLICHFJ", "GJDECBLAJDM", "HOFIOBKIMGP", "EMPHNDEJGCL", "EODFHPDLFNO", "PJNDBKMFIKH", "JJFGEJFFCCC",
				"MBMDOJFBAJN"
			}, new string[1] { "BPIHFAJCLOC" }, null, null, null)
		}));
	}
}
